FROM Python:3.12.4

COPY requirements.txt /tmp/requirements.txt

RUN python -m pip install --timeout 300000 -r /tmp/requirements.txt

COPY . /app


WORKDIR /app

EXPOSE 3000

CMD ["streamlit", "run", 'main.py', "--server.port=8501"]