version: '4'

services:
  api:
    build:
      context: ./api
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8000:80"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: client
    ports:
      - "3000:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
