# Use a slim Python image for a smaller footprint
FROM python:3.12.4

# Set up a working directory
WORKDIR /app

# Copy only requirements.txt first
COPY requirements.txt requirements.txt

# Install Uvicorn and other dependencies 
RUN pip install --no-cache-dir -r requirements.txt

RUN python -m pip install --timeout 300000 -r requirements.txt

# Copy the rest of the application code
COPY  . /app

# Ensure model files are copied into the container
COPY ../Models /app/Models

# Expose the port your app will run on
EXPOSE 80

# Command to run the app
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "80"]